services:
  database:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-pw
    env_file:
      - ./connection.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres-pw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./connection.env
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - postgres-ro-pw

  init-db:
    build: ./db_scripts
    command: ["init"]
    env_file:
      - ./connection.env
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - postgres-pw
      - postgres-ro-pw


  update-db:
    build: ./db_scripts
    command: ["update"]
    env_file:
      - ./connection.env
    volumes:
      - ./log:/log
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - postgres-pw

volumes:
  postgres-data:

secrets:
  postgres-pw:
    file: ./secrets/postgres-pw.txt
  postgres-ro-pw:
    file: ./secrets/postgres-ro-pw.txt
